version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing node packages
      - n 14.15.5
      - rm -rf node_modules
      - #yarn cache clean
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - export REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL
      - export API_BASE_URL=$API_BASE_URL
      - export REACT_APP_IMAGE_UPLOADS_URL=$REACT_APP_IMAGE_UPLOADS_URL
      - export REACT_APP_ORDER_SERVICE_URL=$REACT_APP_ORDER_SERVICE_URL
      - export REACT_APP_GOOGLE_API_KEY=$REACT_APP_GOOGLE_API_KEY
      - export REACT_APP_REPORTS_SERVICE_URL=$REACT_APP_REPORTS_SERVICE_URL
      - export REACT_APP_WMS_BASE_URL=$REACT_APP_WMS_BASE_URL
      - export REACT_APP_OE_BASE_URL=$REACT_APP_OE_BASE_URL
      - export REACT_APP_SHOPCAST_ADAPTOR_BASE_URL=$REACT_APP_SHOPCAST_ADAPTOR_BASE_URL      
      - npm version
      - npm run build
  post_build:
    commands:
      - aws s3 sync dist s3://${S3_BUCKET}
      - aws cloudfront create-invalidation --distribution-id=$PROD_CLOUDFRONT_DIST --paths '/*' 
